---
title: "MTHM501 Assessment Report"
author: "Kevin Donkers (EI CDT) - 700063874"
date: "11/11/2020"
output:
  html_document:
    fig_caption: yes
    smart: no
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE)
```

# Introduction
The UN have Sustainable Development Goals.
One of which is to reduce waste (SDG12?)
However another is to increase human prosperity (SDGX?)
A measure of prosperity if Gross Domestic Product (GDP).

What is the relationship between GDP and household waste?
One theory would be that increased GDP is linked to an increase in consumerism, and so a positive correlation would be expected.
On the other hand, high GDP usually means a country has more money to spend on infrastructure, hence a higher recycling rate would be expected and thus a negative correlation would be expected.

United Nations Statistics Division collects data from member states.

# Objectives
The aim of this investigation is to determine whether there is a relationship 
between national GDP and municipal waste generation. 
After obtaining data from the United Nations Statistics Division, we must tidy the data. 
This involves combining multiple datasets and processing variable so they are comparable.
Next we should visualise each variable to determine how values are distributed,
both statistically and geospatially.
The datasets being merged do not all cover the same set of countries.
Therefore the merged dataset will contain some missing values.
This is addressed by two methods: removal and multiple imputation.
Linear models are fitted to both "corrected" datasets to determine whether GDP and population have an effect on municipal waste generation,
and as an evaluation of the missingness methods.
Limitations of the approach are discussed and final analyses presented in the conclusion.

<!-- 1. Tidy data -->
<!-- 2. Map the data (gdp, waste) -->
<!-- 3. Fix missing data (multiple imputation?) -->
<!-- 4. Linear model across countries (pick a year), across time (pick a country), then multi-variable linear model. -->
<!-- 5*. Factor in population? -->
<!-- 6*. Factor in clustering across regions? -->
<!-- 7. Final analyses presented. -->
<!-- 8. Limitations of approach discussed. -->

# Data
Use data from UNStats
Data on GDP, municipal waste collection per capita, population served by waste collection and population. 
All data is contains annual values 



# Analysis & Results

# Limitations

# Conclusion

\pagebreak

# References

# Data Sources

EU GDP (NAMA_10_GDP) -> https://ec.europa.eu/eurostat/databrowser/view/NAMA_10_GDP__custom_188199/default/table

EU Municipal waste (CEI_PC) -> https://ec.europa.eu/eurostat/databrowser/view/cei_pc031/default/table

---
UN GDP
https://data.un.org/Data.aspx?q=gdp&d=SNAAMA&f=grID:101;currID:USD;pcFlag:1&c=2,3,5,6&s=_crEngNameOrderBy:asc,yr:desc&v=1

UN Waste
https://data.un.org/Data.aspx?q=waste+datamart%5bENV%5d&d=ENV&f=variableID:1814&c=2,3,4,5&s=countryName:asc,yr:desc&v=1

UN Pop
https://data.un.org/Data.aspx?q=population+datamart%5bENV%2cPOP%5d&d=POP&f=tableCode:1&c=2,3,6,8,10,12,13,14&s=_countryEnglishNameOrderBy:asc,refYear:desc,areaCode:asc&v=1

UN Pop served by waste collection
https://data.un.org/Data.aspx?q=waste+datamart%5bENV%5d&d=ENV&f=variableID:1878&c=2,3,4,5&s=countryName:asc,yr:desc&v=1
